apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31112
      name: "gateway"
    - port: 8082
      protocol: TCP
      targetPort: 8082
      name: "prometheus"
  selector:
    app: gateway
