sudo: required

language: go

go:
  - 1.8.x
  
install:
  - echo "Please don't go get"

services:
  - docker

before_script:
- bash contrib/set_travis_experimental_mode.sh
- curl -sSL get.docker.com | sudo -E sh

script:
  - make build
