sudo: required

language: go

go:
  - 1.13.x

install:
  - "echo helm now installed via scripts."

services:
  - docker

before_script:
- bash contrib/set_travis_experimental_mode.sh
- curl -sSLf https://get.docker.com | sed s/sleep\ 20/sleep\ 0/g | sudo -E sh
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - make build
  - ./contrib/get_tools.sh
  - ./contrib/lint_chart.sh
  - ./contrib/create_cluster.sh
  - OPERATOR=0 ./contrib/deploy.sh
  - ./contrib/run_function.sh
  - ./contrib/stop_dev.sh
  - ./contrib/create_cluster.sh
  - OPERATOR=1 ./contrib/deploy.sh
  - OPERATOR=1 ./contrib/run_function.sh
  - ./contrib/stop_dev.sh

after_success:
    - if [ -z $DOCKER_NS ] ; then
        export DOCKER_NS=openfaas;
        fi

    - if [ ! -z "$TRAVIS_TAG" ] ; then
        docker tag $DOCKER_NS/faas-netes:latest $DOCKER_NS/faas-netes:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-netes:$TRAVIS_TAG;

        docker tag $DOCKER_NS/faas-netes:latest quay.io/$DOCKER_NS/faas-netes:$TRAVIS_TAG;
        echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
        docker push quay.io/$DOCKER_NS/faas-netes:$TRAVIS_TAG;

        fi
