{{- if .Values.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: ingress-operator
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: ingress-operator
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ingress-operator
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: ingress-operator
    spec:
      serviceAccountName: ingress-operator
      containers:
      - name: operator
        resources:
          {{- .Values.resources | toYaml | nindent 10 }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - ./ingress-operator
          - -logtostderr
        env:
        - name: function_namespace
          value: {{ .Values.functionNamespace | quote }}
        - name: ingress_namespace
          value: {{ .Release.Namespace | quote }}
{{- end }}
