apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "faas-netesd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gateway
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: gateway
{{- if .Values.exposeServices }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "faas-netesd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gateway-external
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      {{- if contains "NodePort" .Values.serviceType }}
      nodePort: 31112
      {{- end }}
  selector:
    app: gateway
{{- end }}
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "faas-netesd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gateway
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        {{- if .Values.armhf }}
        image: {{ .Values.images.gatewayArmhf }}
        {{- else }}
        image: {{ .Values.images.gateway }}
        {{- end }}
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://faas-netesd.{{ .Release.Namespace }}:8080/"
        {{- if .Values.async }}
        - name: faas_nats_address
          value: "nats.{{ .Release.Namespace }}"
        - name: faas_nats_port
          value: "4222"
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
