{{- if .Values.oidc.enabled }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: oidc
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: oidc
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.oidc.replicas }}
  selector:
    matchLabels:
      app: oidc
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: oidc
    spec:
      volumes:
      - name: oidc-temp-volume
        emptyDir: {}
      {{- if .Values.basic_auth }}
      - name: auth
        secret:
          secretName: basic-auth
      {{- end }}
      containers:
      - name:  oidc
        resources:
          {{- .Values.oidc.resources | toYaml | nindent 12 }}
        image: {{ .Values.oidc.image }}
        imagePullPolicy: {{ .Values.openfaasImagePullPolicy }}
        {{- if .Values.securityContext }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
        {{- end }}
        livenessProbe:
          {{- if .Values.httpProbe }}
          httpGet:
            path: /health
            port: 8080
          {{- else }}
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=5
            - --spider
            - http://localhost:8080/health
          {{- end }}
          timeoutSeconds: 5
        readinessProbe:
          {{- if .Values.httpProbe }}
          httpGet:
            path: /health
            port: 8080
          {{- else }}
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=5
            - --spider
            - http://localhost:8080/health
          {{- end }}
          timeoutSeconds: 5
        args:
        - "-license={{- .Values.oidc.license}}"
        - "-provider={{- .Values.oidc.provider}}"
        env:
        - name: client_id
          value: "{{- .Values.oidc.clientID}}"
        - name: client_secret
          value: "{{- .Values.oidc.clientSecret}}"
        - name: cookie_domain
          value: "{{- .Values.oidc.cookieDomain}}"
        - name: base_host
          value: "{{- .Values.oidc.baseHost}}"
        - name: port
          value: "8080"
        - name: authorize_url
          value: "{{- .Values.oidc.authorizeURL}}"
        - name: welcome_page_url
          value: "{{- .Values.oidc.welcomePageURL}}"
        - name: public_key_path
          value: ""  # leave blank if using jwks
        - name: audience
          value: "{{- .Values.oidc.audience}}"
        - name: token_url
          value: "{{- .Values.oidc.tokenURL}}"
        - name: scopes
          value: "{{- .Values.oidc.scopes}}"
        - name: jwks_url
          value: "{{- .Values.oidc.jwksURL}}"
        - name: insecure_tls
          value: "{{- .Values.oidc.insecureTLS}}"
        {{- if .Values.basic_auth }}
        - name: secret_mount_path
          value: "/var/secrets"
        {{- end }}
        volumeMounts:
        - name: oidc-temp-volume
          mountPath: /tmp
        {{- if .Values.basic_auth }}
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- end }}
