{{- if .Values.psp }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: {{ .Release.Name }}-psp
    labels:
        app: {{ template "openfaas.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
    privileged: false
    allowPrivilegeEscalation: false
    requiredDropCapabilities:
    - ALL
    volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
    hostNetwork: false
    hostIPC: false
    hostPID: false
    readOnlyRootFilesystem: true
    runAsUser:
        rule: MustRunAsNonRoot
    seLinux:
        rule: 'RunAsAny'
    supplementalGroups:
        rule: 'MustRunAs'
        ranges:
        - min: 1
          max: 65535
    fsGroup:
        rule: 'MustRunAs'
        ranges:
        - min: 1
          max: 65535
    readOnlyRootFilesystem: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ .Release.Name }}-psp
    labels:
        app: {{ template "openfaas.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: ['policy']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
          - openfaas-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ .Release.Name }}-psp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ .Release.Name }}-psp
subjects:
    # bind the PSP cluster role to all service accounts in the OF namespace
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:{{ .Release.Namespace }}
      namespace: {{ .Release.Namespace }}
{{- end }}
