{{- if .Values.async }}
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: queue-worker
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: queue-worker
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.queueWorker.replicas }}
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: queue-worker
    spec:
      volumes:
      {{- if .Values.basic_auth }}
      - name: auth
        secret:
          secretName: basic-auth
      {{- end }}
      {{- if .Values.http_signatures }}
      - name: http-signing-private-key
        secret:
          secretName: http-signing-private-key
      {{- end }}
      containers:
      - name:  queue-worker
        image: {{ .Values.queueWorker.image }}
        imagePullPolicy: {{ .Values.openfaasImagePullPolicy }}
        env:
        - name : write_debug
          value : "true"
        {{- if .Values.functionNamespace }}
        - name: faas_function_suffix
          value: ".{{ .Values.functionNamespace }}.svc.{{ .Values.kubernetesDNSDomain }}"
        {{- end }}
        - name: ack_wait    # Max duration of any async task / request
          value: {{ .Values.queueWorker.ackWait }}
        - name: secret_mount_path
          value: "/var/secrets"
        {{- if .Values.basic_auth }}
        - name: basic_auth
          value: "{{ .Values.basic_auth }}"
        {{- end }}
        - name: faas_nats_address
          value: "nats.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesDNSDomain }}"
        volumeMounts:
        {{- if .Values.basic_auth }}
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"
        {{- end }}
        {{- if .Values.http_signatures }}
        - name: http-signing-private-key
          readOnly: true
          mountPath: "/var/secrets"
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
