apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      annotations:
         sidecar.istio.io/inject: "false"
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.16.1
        imagePullPolicy: Always
        command: 
          - "alertmanager"
          - "--config.file=/alertmanager.yml"
          - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9003
          protocol: TCP
        resources:
          requests:
            memory: 25Mi
          limits:
            memory: 50Mi
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644
        - name: auth
          secret:
            secretName: basic-auth
