apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: queue-worker
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
      containers:
      - name:  queue-worker
        image: openfaas/queue-worker:0.7.1
        imagePullPolicy: Always
        env:
        - name: max_inflight      # Max number of items in-flight
          value: "1"
        - name: ack_wait          # Max duration of any async task / request
          value: "30s"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local."  # absolute DNS will suppress search domains
        - name: secret_mount_path
          value: "/var/secrets"
        - name: basic_auth
          value: "{{ .Values.basic_auth }}"
        volumeMounts:
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"

