name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: build
        run: make build
      - name: get tools
        run: ./contrib/get_tools.sh
      - name: lint chart
        run: ./contrib/lint_chart.sh
      - name: create cluster
        run: ./contrib/create_cluster.sh
      - name: deploy function
        run: OPERATOR=0 ./contrib/deploy.sh
      - name: run function
        run: OPERATOR=0 ./contrib/run_function.sh
      - name: stop dev cluster
        run: ./contrib/stop_dev.sh
      - name: wait 10 seconds
        run: sleep 10
      - name: create cluster
        run: ./contrib/create_cluster.sh
      - name: deploy function
        run: OPERATOR=1 ./contrib/deploy.sh
      - name: run function
        run: OPERATOR=1 ./contrib/run_function.sh
      - name: stop dev cluster
        run: ./contrib/stop_dev.sh


